/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
/*
 * Copyright 2017-2025 noear.org and authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.noear.gradle.plugin

/**
 * A simple unit test for the 'com.noear.gradle.plugin.greeting' plugin.
 */
class SolonGradlePluginPluginTest {
//    @Test fun `plugin registers task`() {
//        // Create a test project and apply the plugin
//        val project = ProjectBuilder.builder().build()
//        project.plugins.apply("org.noear.solon")
//
//        // Verify the result
//        assertNotNull(project.tasks.findByName("solonJar"))
//    }
}
