/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.noear.gradle.plugin

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'com.noear.gradle.plugin.greeting' plugin.
 */
class SolonGradlePluginPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("org.noear.solon")

        // Verify the result
        assertNotNull(project.tasks.findByName("solonJar"))
    }
}
