@startuml
start
:扫描Source下的所有类;
:发现有注解的类;
:生成BeanWrap;
if(BeanWrap.raw() != null) then(yes)
    :type 注册+通知;
else
    :不注册;
endif
:执行注解代理;
fork
  :如果有name?;
  :name 注册+通知;
fork again
  :如是是接口?;
  :完成接口代理;
  :生成新的BeanWrap;
  :type 注册+通知;
  if(如果有父接口) then(yes)
    :父接口 type 注册+通知;
  endif
end fork
stop
@enduml