/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/global_layout/Footer.vue')['default']
    Global_layout: typeof import('./src/components/global_layout/index.vue')['default']
    Header: typeof import('./src/components/global_layout/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VChart: typeof import('vue-echarts')['default']
  }
}
