/**
 *@Generated by sagacity-quickvo 4.18
 */
package com.sqltoy.helloworld.vo;

import com.sqltoy.helloworld.vo.base.AbstractFruitOrderVO;
import org.sagacity.sqltoy.config.annotation.SqlToyEntity;

/**
 * @project sqltoy-helloworld
 * @author zhongxuchen
 * @version 1.0.0
 * Table: sqltoy_fruit_order,Remark:查询汇总演示-水果订单表
 */
@SqlToyEntity
public class FruitOrderVO extends AbstractFruitOrderVO {
	/**
	 *
	 */
	private static final long serialVersionUID = 5063892117644384071L;

	/** default constructor */
	public FruitOrderVO() {
		super();
	}

	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public FruitOrderVO(String fruitName,Integer orderMonth)
	{
		this.fruitName=fruitName;
		this.orderMonth=orderMonth;
	}
	/*---end-constructor-area---don't-update-this-area--*/

	/**
     * @todo vo columns to String
     */
    @Override
	public String toString() {
		return super.toString();
	}

	/*
	 * (non-Javadoc)
	 *
	 * @see java.lang.Object#clone()
	 */
	@Override
	public FruitOrderVO clone() {
		try {
			return (FruitOrderVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}

}
