// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Example.proto

package io.github.majusko.pulsar.msg;

public interface ProtoMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.github.majusko.pulsar.msg.ProtoMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string data = 1;</code>
   */
  String getData();
  /**
   * <code>string data = 1;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
